### ISSUE TITLE
Cargo fix transition to 2018 edition url is wrong

### ISSUE THREAD

**Issue by orium** [rust-lang-nursery/rustfix#143]
Just came across an error message where cargo-fix points me to a broken url: https://rust-lang-nursery.github.io/edition-guide/editions/transitioning.html

```
error: cannot prepare for the 2018 edition when it is enabled, so cargo cannot
automatically fix errors in `src/lib.rs`

To prepare for the 2018 edition you should first remove `edition = '2018'` from
your `Cargo.toml` and then rerun this command. Once all warnings have been fixed
then you can re-enable the `edition` key in `Cargo.toml`. For some more
information about transitioning to the 2018 edition see:

  https://rust-lang-nursery.github.io/edition-guide/editions/transitioning.html
```

**Comment by killercup** [comment]
Hey, thanks for the report!

It seems to me like the page is now called https://rust-lang-nursery.github.io/edition-guide/editions/transitioning-your-code-to-a-new-edition.html -- cc @steveklabnik for confirmation and to drop off a "cool URLs don't change" along the way :)

This is actually an issue in cargo though -- because it's part of the cargo-fix command. Can you close this issue open it again on <https://github.com/rust-lang/cargo/issues>? (Otherwise I can do it, no worries.) Did the tool tell you to report an issue in this repo? If so we might have too URLs to fix!

**Comment by orium** [comment]
> This is actually an issue in cargo though -- because it's part of the cargo-fix command. Can you close this issue open it again on https://github.com/rust-lang/cargo/issues?

My bad.  Created PR in rust-lang/cargo: rust-lang/cargo#5900

> Did the tool tell you to report an issue in this repo? If so we might have too URLs to fix!

No.  This is not a bug unless for the broken url.

**Comment by killercup** [comment]
Perfect, thank you!
